### ISSUE TITLE
Services fail to start with Error: Invalid or corrupt jarfile 

### ISSUE THREAD

**Issue by ccondit** [SciCrunch/SciGraph#103]
Looks like we're running up against the [limits of the shade zip file](http://stackoverflow.com/questions/13021423/invalid-or-corrupt-jar-file-built-by-maven-shade-plugin).

**Comment by ccondit** [comment]
@llui would you please try this out with the Bamboo deployments?

**Comment by lawrencellui** [comment]
All SciGraph service builds have been updated to use the new zip file.
