### ISSUE TITLE
graph/path - Order results by shortest paths

### ISSUE THREAD

**Issue by cmungall** [SciCrunch/SciGraph#2]
Example: 

http://beta.neuinfo.org/graphdemo/graph/path/simple/UBERON_0002398/UBERON_0002101.json?length=3&callback=fn

The two-step over part_of and subClassOf should be shown first.

TBD: should each topology graph object also indicate the length of the path? This may make it easier for clients (e.g. to filter by path length on the client side). In future we will also want to score paths, so the json structure should be extensible to this

**Comment by ccondit** [comment]
This service has been removed.
