### ISSUE TITLE
Adding the right ontologies and data sets

### ISSUE THREAD

**Issue by aguptasd** [SciCrunch/SciGraph#23]
I have discussed this with both Melissa and Nicole. It would like to construct at least one end-to-end example of a path that traverses like this:
disease > phenotype > related phenotype > gene > related gene > pathway > drug target> drug
Several of these steps can be chains in reality -- some of them can be computationally connected through OWLSim or other means.

What data/ontology do we need to import to construct such a hand-crafted example?

**Comment by ccondit** [comment]
@nlwashington can this be closed with the Dipper / SciGraph work?

**Comment by nlwashington** [comment]
i think we have some nice use cases solved with the appropriate datasets, as documented in our dgocs.  see me for help if you want access.
