### ISSUE TITLE
populate a Solr instance from SciGraph

### ISSUE THREAD

**Issue by cmungall** [SciCrunch/SciGraph#36]
Background: we will use SciGraph for graph-oriented or complex queries, especially those involving paths. For fast browsing of data tables we will continue to use Solr or similar denormalized faceted solutions. We will need a way to populate part or all of a Solr index from SciGraph.

To populate datafederation (ie nif) Solr cores, this may be as simple as passing a cypher query through the existing JDBC federation loader. @ccondit will investigate. Open questions here include: will this scale for large joins?

We also need to be able to add Solr documents that follow the GOlr meta-schema. This will require separate code. Rough overview: a yaml file provides metadata as to which fields we would need to cache ancestry for. The solr loader would consume this yaml, iterate through all SG nodes to be indexed, populating documents with the ancestors included. cc @kltm @hdietze

**Comment by ccondit** [comment]
@cmungall - is this resolved with the Golr work?

**Comment by ccondit** [comment]
Replaced by #46
