### ISSUE TITLE
Exporting graph data

### ISSUE THREAD

**Issue by cmungall** [SciCrunch/SciGraph#5]
Many bioinformaticians require entire dumps (rather than REST queries that return N results at a time).

In some ways this isn't SciGraph's concern as currently the data comes from a uniform set of RDF/OWL, anyone can take this at source.

But it may still be useful to get custom dumps based on some criteria. It would be good to think about this upfront.

**Comment by ccondit** [comment]
Added a writer for XGMML (media type: application/xgmml, suffix .gr). So now SciGraph supports:

* bbop json
* graphml
* graphson
* gml
* xgmml
* png
* jpeg

These can all be used with either the dynamic, template queries or the usual graph services.
