### ISSUE TITLE
findByPrefix needs to sort results then limit

### ISSUE THREAD

**Issue by twhetzel** [SciCrunch/SciGraph#51]
The findByPrefix call[1] does not return the concept kidney when using:
http://matrix.neuinfo.org:9000/scigraph/vocabulary/autocomplete/kidney?limit=20&searchSynonyms=true
Based on discussion at the architecture meeting it seemed that the issue was that the results needed to be sorted first and then limited since when the limit is set to 100 the concept is returned.

[1] http://matrix.neuinfo.org:9000/scigraph/docs/#!/vocabulary/findByPrefix

**Comment by ccondit** [comment]
How do you want these to be sorted - just alphabetically?

**Comment by twhetzel** [comment]
Sorting alphabetically seems fine. Is that how the autocomplete service currently works from Ontoquest?
