### ISSUE TITLE
suggestFromTerm

### ISSUE THREAD

**Issue by twhetzel** [SciCrunch/SciGraph#53]
There seem to be some differences in the SciGraph call suggestFromTerm[1] vs. the OQ call[2]

- the '+' sign behaves differently in SciGraph, glial+c with limit=10 returns glial cell and glial scar, while the OQ call returns glial and all terms with glial and a second token starting with 'c'. Is that change intended?
- can the suggestions be limited to a subtree and category as with the OQ call?

[1] http://matrix.neuinfo.org:9000/scigraph/docs/#!/vocabulary/suggestFromTerm
[2] https://confluence.crbs.ucsd.edu/display/NIF/OntoQuestMain#OntoQuestMain-10%29Searchtermsstartingwiththequery%28usedforauto-completeservice%29:%28updatedon03/10/2010%29

**Comment by ccondit** [comment]
* http://matrix.neuinfo.org:9000/scigraph/vocabulary/autocomplete/glial%20c?limit=20&searchSynonyms=true is the corresponding SciGraph call. The suggestion resource is for misspelled terms like http://matrix.neuinfo.org:9000/scigraph/vocabulary/suggestions/hippocrampus?limit=1
* The autocompletion API can be limited by category: http://matrix.neuinfo.org:9000/scigraph/docs/#!/vocabulary/findByPrefix
