### ISSUE TITLE
neighbors and subgraph queries

### ISSUE THREAD

**Issue by cmungall** [SciCrunch/SciGraph#55]
## Preliminaries

bbop-js provides a simple json format for representing graphs (akin to gml etc). See [graphs](https://github.com/kltm/bbop-js/wiki/Graph) for details, or contact @kltm.

Within the same format there are two flavours:

 1. [TopologyGraph](https://github.com/kltm/bbop-js/wiki/TopologyGraph)
 2. [TransitivityGraph](https://github.com/kltm/bbop-js/wiki/TransitivityGraph)

Briefly:

a topology graph is all nodes from the query node to root, plus all *direct* edges connecting these nodes

a transitivity graph is all *direct and indirect* edges from the query graph to any ancestor

(my explanation is more OWLAPI-ish than @kltm's. Also omitting filtering by edge type and default extending to descendants by distance=1 for brevity)

Thus with a graph A->B->C, 

```
Topol(A) has edges {A->B, B->C}
Trans(A) has edges {A->B, A->C}
```

We are mostly concerned with topology graphs here. Transitivity graphs are useful for precomputing the closure for storing in solr etc.

## Current /neighbors/ query

This was implemented to support the cytoscape.js demo in monarch labs. It's probably not optimal for other purposes. It computes the distinct *paths* between nodes, where each path is represented as its own TopologyGraph. Thus if we have A->B->{C,D} then we have 

   paths for A with depth(2) = [{A->B,B->C}, {A->B},{B->D}]

This is suboptimal for purposes such as drawing a graph; in fact it's not clear why this is required for the cytoscape demo.

## Desired behavior

In the above example, for most purposes such as visualizing ancestors to a certain depth, we just want the straightforward topology graph for a node (but truncated to a specified depth). So for the example above, the payload would be a bbop-formatted topology graph with edges

    {A->B, B->C, B->D}

To avoid confusion we should probably not use /neighbors{n}/. My preference is simply for /subgraph/

Parameters:

 * query id: the 'topic' node. We may want to allow multiple values
 * ancestors_depth : number of hops up (default is infinity; to the root)
 * descendant_depth: defaults to either 0 or 1 (1 is consistent with bbop topology graph specification)
 * relations: set of relations to include. defaults to just subClassOf

**Comment by cmungall** [comment]
Use the ontology lattice.owl for testing

This is the intersection of two trees, A and B,

A=
```
a1
 a12
  a111
  a112
 a12
  a121
  a122
a2
 a21
  a211
  a212
 a22
  a221
  a222
```
B parallels A

We also include the cross-product of A x B, thus every class in the cross-product has two inferred parents in the cross-product.

**Comment by ccondit** [comment]
> Parameters:
> query id: the 'topic' node. We may want to allow multiple values

I do like the simplicity of `/graph/neighbors/HPO_1`. Should we change this to `graph/neighbors?id=HPO_1&id=HPO_2`?

> ancestors_depth : number of hops up (default is infinity; to the root)
> descendant_depth: defaults to either 0 or 1 (1 is consistent with bbop topology graph specification)

Why are descendants needed? It seems like a cleaner design to stick to a single direction. Or have the client make two calls.

> relations: set of relations to include. defaults to just subClassOf

I think this should default to all relationships allowing the client to inspect them if necessary. And do the relations all need to have a direction specified? Or should they all use the same direction?

We'll also need a parameter for traversing blank nodes or not.

How should node properties be returned? Seems like some clients might want very little detail back (for displaying structure) while others may want all the properties returned.

**Comment by cmungall** [comment]
On 7 Jan 2015, at 12:08, Chris Condit wrote:

>> Parameters:
>> query id: the 'topic' node. We may want to allow multiple values
>
> I do like the simplicity of `/graph/neighbors/HPO_1`. Should we change 
> this to `graph/neighbors?id=HPO_1&id=HPO_2`?

How about

/graph/neighbors/HPO_1+HPO+2


>> ancestors_depth : number of hops up (default is infinity; to the 
>> root)
>> descendant_depth: defaults to either 0 or 1 (1 is consistent with 
>> bbop topology graph specification)
>
> Why are descendants needed? It seems like a cleaner design to stick to 
> a single direction. Or have the client make two calls.

For the visualization use case, it's frequently convenient to see one 
level down. Making two calls may have separate semantic, as the 
TopologyGraph includes all edges between nodes in the two sets. With two 
calls you end up omitting edges X->[R]->Y where X is in the ancestor set 
and Y is in the child set.

It seems there is a tension between clean design and flexibility. At one 
extreme you have things like Gremlin and Cypher, at the other simple 
restful calls with a small set of well-defined parameters. We'll often 
want stuff in the middle…

But for now you can eliminate children

>> relations: set of relations to include. defaults to just subClassOf
>
> I think this should default to all relationships allowing the client 
> to inspect them if necessary.

OK. Note that path to root (infinite max hops) is potentially explosive.

> And do the relations all need to have a direction specified? Or should 
> they all use the same direction?

Should always be subject->object for an ancestors query

> We'll also need a parameter for traversing blank nodes or not.

yes

> How should node properties be returned? Seems like some clients might 
> want very little detail back (for displaying structure) while others 
> may want all the properties returned.

A decent default set may be ID/CURIE, label and category.

**Comment by harryhoch** [comment]
Chris:

that all sounds completely reasonable to me.

-harry

On Jan 7, 2015, at 3:29 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:



On 7 Jan 2015, at 12:08, Chris Condit wrote:

>> Parameters:
>> query id: the 'topic' node. We may want to allow multiple values
>
> I do like the simplicity of `/graph/neighbors/HPO_1`. Should we change
> this to `graph/neighbors?id=HPO_1&id=HPO_2`?

How about

/graph/neighbors/HPO_1+HPO+2


>> ancestors_depth : number of hops up (default is infinity; to the
>> root)
>> descendant_depth: defaults to either 0 or 1 (1 is consistent with
>> bbop topology graph specification)
>
> Why are descendants needed? It seems like a cleaner design to stick to
> a single direction. Or have the client make two calls.

For the visualization use case, it's frequently convenient to see one
level down. Making two calls may have separate semantic, as the
TopologyGraph includes all edges between nodes in the two sets. With two
calls you end up omitting edges X->[R]->Y where X is in the ancestor set
and Y is in the child set.

It seems there is a tension between clean design and flexibility. At one
extreme you have things like Gremlin and Cypher, at the other simple
restful calls with a small set of well-defined parameters. We'll often
want stuff in the middle…

But for now you can eliminate children

>> relations: set of relations to include. defaults to just subClassOf
>
> I think this should default to all relationships allowing the client
> to inspect them if necessary.

OK. Note that path to root (infinite max hops) is potentially explosive.

> And do the relations all need to have a direction specified? Or should
> they all use the same direction?

Should always be subject->object for an ancestors query

> We'll also need a parameter for traversing blank nodes or not.

yes

> How should node properties be returned? Seems like some clients might
> want very little detail back (for displaying structure) while others
> may want all the properties returned.

A decent default set may be ID/CURIE, label and category.

—
Reply to this email directly or view it on GitHub<https://github.com/SciCrunch/SciGraph/issues/55#issuecomment-69086543>.

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics
harryh@pitt.edu<mailto:harryh@pitt.edu>  412 648 9300

**Comment by ccondit** [comment]
Added a REST endpoint supporting multiple root IDs for the subgraph query:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/docs/#!/graph/getNeighborsFromMultipleRoots

**Comment by ccondit** [comment]
Added categories to the bbop output
