### ISSUE TITLE
Filter deprecated classes from the findByPrefix call

### ISSUE THREAD

**Issue by twhetzel** [SciCrunch/SciGraph#59]
The findByPrefix call [1] returns classes that are deprecated. To be consistent with the autocomplete behavior on neuinfo.org, classes that are deprecated should not be displayed as options in the autocomplete.  E.g. the deprecated classes metastasis to the kidney and polycystic kidney disease (DOID_5898) are returned by the autocomplete scigraph service.

[1] http://matrix.neuinfo.org:9000/scigraph/docs/#!/vocabulary/findByPrefix

**Comment by nlwashington** [comment]
Hopefully deprecated classes can still be available as an option.

**Comment by twhetzel** [comment]
@nlwashington does Monarch have a requirement that deprecated classes should be available from the autocomplete?
