### ISSUE TITLE
Autocomplete should return results when an abbreviation is the search term

### ISSUE THREAD

**Issue by twhetzel** [SciCrunch/SciGraph#65]
Anita mentioned that the autocomplete service should return suggestions when the abbreviation of a term is entered. In reviewing the autocomplete web service [1] using c11n as the input term no results are returned, however when the preferred label of this term is used [2] accessory nerve root results are returned. c11n is an abbreviation for http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-GrossAnatomy.owl#birnlex_1580 and the abbreviation value is returned in the information about this concept, which is modeled using http://ontology.neuinfo.org/NIF/Backend/OBO_annotation_properties.owl#abbrev and listed in the YAML file of mappedProperties.

[1] http://matrix.neuinfo.org:9000/scigraph/vocabulary/autocomplete/c11n?limit=20&searchSynonyms=true&includeDeprecated=false
[2] http://matrix.neuinfo.org:9000/scigraph/vocabulary/autocomplete/accessory%20nerve%20root?limit=20&searchSynonyms=true&includeDeprecated=false

cc @bandrow @jgrethe

**Comment by cmungall** [comment]
I don't know if this is a SC requirement but many ontologies follow the uberon model for synonyms:

https://github.com/obophenotype/uberon/wiki/Using-uberon-for-text-mining

**Comment by ccondit** [comment]
see:
http://matrix.neuinfo.org:9000/scigraph/vocabulary/autocomplete/vis%20syst?limit=20&searchAbbreviations=true
