### ISSUE TITLE
template queries

### ISSUE THREAD

**Issue by nlwashington** [SciCrunch/SciGraph#66]
We'd like to add template queries as services to SciGraph.

Some examples to solve:

1.  what are the genotypes that involve my gene?
2.  what are the phenotypes associated with my gene?
3.  what are the phenotypes associated with my disease?
4.  what publications mention my gene?
5.  with what genes does my gene interact?
6.  what are the orthologs of my gene?

**Comment by memartone** [comment]
We have something like that for ONtoquest (the FIND command), e.g., FIND:gene cerebellum, finds all references to cerebellum that had a column mapped to gene.

Maryann Martone, Ph. D.
Professor-in-Residence
Department of Neuroscience
University of California, San Diego
San Diego, CA 92093-0446

858-822-0745

**Comment by ccondit** [comment]
Would be great to configure these templates with the YAML for the application. The only hitch is that Jersey 1.19 (which DropWizard 0.7.2 uses) doesn't support programmatically generating resources (AFAIK). Dropwizard 0.8.0 will switch to Jersey 2.x which will allow this. Currently this is at RC2 and from the look of the repository they're getting ready for a final release.

**Comment by nathandunn** [comment]
@nlwashington   @ccondit  Some additional queries:
- coordinates given a chromosome
- coordinates given the chromosome sub-band: (\d+|A-Z)[pq]\d+\.\d+
20 -> 20q -> 20q1 -> 20q13 -> 20q12.3 ->20q12.33
- coordinates given a gene (min and max only necessary)

**Comment by nathandunn** [comment]
Related to:  https://github.com/monarch-initiative/monarch-app/issues/653

Specifically on the phenotype pages I need access to the genes with that data (right now calling the gene page with the JSON extension and grabbing that data).

**Comment by ccondit** [comment]
I've also added a Cypher hack to allow the template queries to request all subObjectProperties of a relationship. For instance:
MATCH (n)-[r:TYPE!]-(m)
RETURN n,r,m
Will return `r`s with TYPE or any of its descendants.

This can also be used with multiple types: [:TYPE|TYPE2!]

**Comment by nathandunn** [comment]
@ccondit   Is this ready to test?  No worries if not.

**Comment by ccondit** [comment]
@nathandunn Very close. What are you initial use cases?

**Comment by nathandunn** [comment]
Sure.  The initial ones will be: 
- select all variants for phenotype: HP:0001298 and organism Human
- select all variants for disease:  OMIM:613759 and organism Human

Variant information should include:
- location 
- chromosome
- gene (if available)
- any other meta-information on the variant

**Comment by nlwashington** [comment]
Ok, so a couple of questions.  If I give you a list of identifiers for genomic features linked to the phenotype query, can you look up the locations yourself?

For example, if what is connected to a phenotype or disease is a gene, can i return to you the gene id (that you can then look up the coordinates?)  At the moment we don't have location information other than chromosome (and sometimes chr band).  But you do!

**Comment by nathandunn** [comment]
Hmm . . unfortunately, that doesn't tell me where to draw the variant, just what gene it is in. 

Another option would be to have:
1 - a unique ID for the specific variants
2 - an all-inclusive variant track with the same ID's (if you have the GFF3 source, I can convert). 

It could be that we fork whatever your incoming source for creating the variants is (is this deja vu) to create the GFF3 file.

**Comment by nlwashington** [comment]
so, the thing is, eventually we're going to have phenotype data attached to all different levels of genomic granularity.  sometimes it'll be at the gene level, sometimes at a large genomic interval, and sometimes at a specific base pair.  you really want to get back the features that are attached to the query phenotype.  now, if you're use case here is only for variants, you'll have to wait awhile, as we haven't taken in the variant-to-phenotype data from clinvar yet.

**Comment by nathandunn** [comment]
Is there anything that variants are linked to that we can use? 

Nathan

**Comment by nlwashington** [comment]
there are currently no variants loaded into scigraph.

**Comment by nathandunn** [comment]
I see.  Sorry, I thought we had them in there or they were going to be in there soon.

Taking a step back, we should be able to get associated genes for a phenotype / disease through a single SciGraph call, right?     That use-case will be helpful. 

As for variants:
1 - are we planning on getting them into SciGraph in the future?   
2 - if not there, is there another place we can query them from? 

Nathan

**Comment by nathandunn** [comment]
@nlwashington   says that she can likely get me a mapping from a phenotype -> Gene  where Gene also has chromosome location and organism information .  . all out of the same request.   That should be sufficient.

**Comment by ccondit** [comment]
Added some initial implementations here:
http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/phenotypes_with_gene.json?gene_id={gene_id}
http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genes_with_phenotype.json?phenotype_id={phenotype_id}
http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genotypes_from_gene.json?gene_id={gene_id}

**Comment by ccondit** [comment]
@nlwashington let me know when DIPPER is ready to supply the rest of the data to finish these queries...

**Comment by nlwashington** [comment]
@harryhoch these are the examples i indicated we can query for phenogrid... monarch-app can wrap these.  for example, http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genotypes_from_gene.json?gene_id=ZDB-GENE-070117-1709

**Comment by harryhoch** [comment]
thanks. Just so I understand, will those calls be migrating to kato? 

> On Feb 26, 2015, at 7:29 PM, Nicole Washington <notifications@github.com> wrote:
> 
> @harryhoch these are the examples i indicated we can query for phenogrid... monarch-app can wrap these. for example, http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genotypes_from_gene.json?gene_id=ZDB-GENE-070117-1709
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by ccondit** [comment]
> thanks. Just so I understand, will those calls be migrating to kato?

rosie has a larger graph than the current monarch production. It will
either migrate to kato or to some other production VM.

It will stay on rosie for a while until we get all the issues ironed out.

**Comment by harryhoch** [comment]
ok, so I can point monarch-app @ rosie instead of kata? thanks for clarifying. 
> On 27 Feb 2015, at 12:23 PM, Chris Condit <notifications@github.com> wrote:
> 
> > thanks. Just so I understand, will those calls be migrating to kato?
> 
> rosie has a larger graph than the current monarch production. It will
> either migrate to kato or to some other production VM.
> 
> It will stay on rosie for a while until we get all the issues ironed out.
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by ccondit** [comment]
> ok, so I can point monarch-app @ rosie instead of kata? thanks for clarifying.

At this point they do not expose the same set of services. rosie is
for structural graph queries while kato has the vocabulary services
for monarch.owl.

**Comment by harryhoch** [comment]
got it. thanks. This would seem to imply that _both_ will be needed for monarch-app - correct?
> On 27 Feb 2015, at 12:44 PM, Chris Condit <notifications@github.com> wrote:
> 
> > ok, so I can point monarch-app @ rosie instead of kata? thanks for clarifying.
> 
> At this point they do not expose the same set of services. rosie is
> for structural graph queries while kato has the vocabulary services
> for monarch.owl.
> 
> > > On 27 Feb 2015, at 12:23 PM, Chris Condit <notifications@github.com> wrote:
> > >
> > > > thanks. Just so I understand, will those calls be migrating to kato?
> > >
> > > rosie has a larger graph than the current monarch production. It will
> > > either migrate to kato or to some other production VM.
> > >
> > > It will stay on rosie for a while until we get all the issues ironed out.
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > ----
> > Harry Hochheiser
> > University of Pittsburgh
> > Department of Biomedical Informatics
> > harryh@pitt.edu 412 648 9300
> >
> >
> >
> >
> >
> >
> >
> >
> > —
> >
> >
> > Reply to this email directly or view it on GitHub.
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by ccondit** [comment]
> got it. thanks. This would seem to imply that _both_ will be needed for
> monarch-app - correct?

Potentially. We still need to do some research to figure out the best
deployment plan. The unknown is if clients actually want to
autocomplete on all the entities in the larger graph.

**Comment by harryhoch** [comment]
ok, thanks. short-term for dev/testing purposes, we might need to use both...
> On 27 Feb 2015, at 12:51 PM, Chris Condit <notifications@github.com> wrote:
> 
> > got it. thanks. This would seem to imply that _both_ will be needed for
> > monarch-app - correct?
> 
> Potentially. We still need to do some research to figure out the best
> deployment plan. The unknown is if clients actually want to
> autocomplete on all the entities in the larger graph.
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by nlwashington** [comment]
can you do this one next?
what are the orthologs of my gene?

ideally, i can also submit a list of genes, and get back the orthologs for the whole list.

**Comment by ccondit** [comment]
Will add a way to add the relationship type as a parameter (this is not built into cypher).

**Comment by ccondit** [comment]
Add a way to specify logical defaults for Cypher queries that the user can override...

**Comment by ccondit** [comment]
Template queries are functional. Let's take updates as new feature requests...
