### ISSUE TITLE
exact matches missing from suggestions

### ISSUE THREAD

**Issue by nlwashington** [SciCrunch/SciGraph#69]
I think the suggestion service is not working correctly.  

For example:
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/suggestions/shh?limit=1&callback=fn

i would expect to get back exact matches in the result.  why don't i?

also, i would expect to get partial matches back, why don't i? for example:
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/suggestions/MEF2BNB?limit=1&callback=fn
but this is found as the start of the term:
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/term/MEF2BNB-MEF2B?limit=20&searchSynonyms=true&callback=fn

(or is that by design?)

**Comment by ccondit** [comment]
I think you're looking for the autocomplete resource:
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/shh?limit=1&callback=fn
and
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/MEF2BNB?limit=1&callback=fn

Are those the results you expect?

**Comment by nlwashington** [comment]
Well, not exactly.  Why do i get different results between the term and autocomplete?
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/MEF2BNB?limit=1&callback=fn
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/term/MEF2BNB?limit=1&callback=fn

and why don't I get 
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/search/MEF2BNB-MEF2B?limit=1&callback=fn ?

**Comment by nlwashington** [comment]
oh wait, if i increase the limit, i see the other terms in autocomplete.

**Comment by twhetzel** [comment]
We had the same (or very similar) issue in our instance of SciGraph for NIFSTD and requested an update, which fixed this issue. @ccondit is this the same issue and are updates applied to SciGraph that propagate to all instances?

**Comment by ccondit** [comment]
Oh yes. I think this is resolved on alpha:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/MEF2BNB?limit=1

**Comment by nlwashington** [comment]
i think you're right.
