### ISSUE TITLE
Annotation service and UTF-8 encoding

### ISSUE THREAD

**Issue by ccondit** [SciCrunch/SciGraph#75]
For UTF-8 encoded input such as "HNF-1β" the annotation services do not return UTF-8 encoded results. The response is in Latin1 (default Java) encoding not properly handling non Latin1 characters such as greek letters abundant in biological entities such as protein names.

**Comment by ccondit** [comment]
Note this only affected the service returning text/plain.

**Comment by bozyurt** [comment]
Hi Chris,

Does this fix affect the POST version also ?

Burak

I. Burak Ozyurt, PhD
Associate Project Scientist
UCSD Dept of Psychiatry
9500 Gilman Drive MC 0855
La Jolla, CA 92093-0855
Tel: 858-246-0606
________________________________

**Comment by ccondit** [comment]
This was actually a UNIX issue - the JVM needs to be started with -Dfile.encoding=UTF-8. This is running on matrix and should propagate to all the SciGraph servers when they're reloaded.
