### ISSUE TITLE
getShortestPath has 500 error

### ISSUE THREAD

**Issue by nlwashington** [SciCrunch/SciGraph#76]
I tried this query:

http://kato.crbs.ucsd.edu:9000/scigraph/graph/paths/short/HP_0000524/HP_0000118?length=10&callback=fn

but it doesn't work at all.  are shortest path queries offline?  i get a 500 error.

**Comment by ccondit** [comment]
This service has been removed due to performance concerns.

**Comment by ccondit** [comment]
Can we make a template query for what you want to do?
