### ISSUE TITLE
Autocomplete service displays deprecated terms when includeDeprecated=false

### ISSUE THREAD

**Issue by twhetzel** [SciCrunch/SciGraph#79]
When using the autocomplete service e.g. http://matrix.neuinfo.org:9000/scigraph/vocabulary/autocomplete/NCI?limit=20&searchSynonyms=true&searchAbbreviations=true&searchAcronyms=true&includeDeprecated=false, deprecated terms, http://ontology.neuinfo.org/NIF/DigitalEntities/NIF-Government-Granting-Agency.owl#nlx_inv_1005051, are displayed when the flag  includeDeprecated=false.

**Comment by ccondit** [comment]
This is the declaration that I see for this class:

    <owl:Class rdf:about="http://ontology.neuinfo.org/NIF/DigitalEntities/NIF-Government-Granting-Agency.owl#nlx_inv_1005051">
      <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Division of cancer epidemiology and genetics</rdfs:label>
      <rdfs:subClassOf rdf:resource="http://ontology.neuinfo.org/NIF/DigitalEntities/NIF-Investigation.owl#birnlex_2431"/>
      <rdfs:subClassOf>
        <owl:Restriction>
          <owl:onProperty rdf:resource="http://www.obofoundry.org/ro.owl#part_of"/>
          <owl:someValuesFrom rdf:resource="http://ontology.neuinfo.org/NIF/DigitalEntities/NIF-Government-Granting-Agency.owl#nlx_inv_1005082"/>
        </owl:Restriction>
      </rdfs:subClassOf>
      <obo_annot:synonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string"/>
      <dc:contributor rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Anita Bandrowski</dc:contributor>
      <obo_annot:createdDate rdf:datatype="http://www.w3.org/2001/XMLSchema#string">May 20, 2010</obo_annot:createdDate>
      <obo_annot:modifiedDate rdf:datatype="http://www.w3.org/2001/XMLSchema#string">May 26, 2010</obo_annot:modifiedDate>
      <obo_annot:abbrev rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCI</obo_annot:abbrev>
      <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">This agancy is part of National cancer institute</rdfs:comment>
      <dc:description rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://www.cancer.gov/researchandfunding</dc:description>
    </owl:Class>

It does not appear to be deprecated.

**Comment by cmungall** [comment]
While we're here:

  * s/agancy/agency/
  * should be modeled as individual, not a class
  * http://www.obofoundry.org/ro.owl# is a deprecated ontology
  * This class has a synonym of "" -- this is potentially very 
problematic. Note the semantics are different than having no synonym.
  * dates should be modeled as xsd:dates - or at least should conform to 
ISO 8601
  * the description field doesn't hold a description. A different 
property with either a rdf:resource or xsd:anyURI value should be used.

**Comment by twhetzel** [comment]
Yup, these are all things that have to be clean-up in NIFSTD .. but have nothing to do with my misread of what the autocomplete service should be returning.
