### ISSUE TITLE
new query for feature-to-phenotype

### ISSUE THREAD

**Issue by nlwashington** [SciCrunch/SciGraph#83]
similar to the gene-to-phenotype query, we really want any kind of sequence feature to phenotype query.  really, a "gene" is a specific kind of sequence feature here.  

"feature" here are subclasses or instances of SO:0000110.

feature-to-phenotype relationships may happen directly, or the feature may be part of a genotype.

using the MGI data as an example
MGI:2172552 has_phenotype MP:0003727
and
MGI:2172552 has_alternate_part* MGI:1857543  #this is the feature
(in this gene: MGI:97451)

**Comment by nlwashington** [comment]
and we'd want the reciprocal ones too.

**Comment by ccondit** [comment]
Implemented on rosie
