### ISSUE TITLE
Load new version of scicrunch-registry.owl

### ISSUE THREAD

**Issue by twhetzel** [SciCrunch/SciGraph#84]
To populate the autocomplete for SciCrunch to display resources and organizations, can you load this updated version of the scicrunch-registry.owl file:
http://ontology.neuinfo.org/SciCrunchRegistry/scicrunch-registry.owl
 
cc @bandrow

**Comment by ccondit** [comment]
I reloaded the graph

**Comment by twhetzel** [comment]
@debanks are the services on Alpha.scicrunch.com/dknet pointing to this content for the autocomplete? The response on the web site does not look like the information in the OWL file.

**Comment by debanks** [comment]
currently both alpha and stage are pointing to cypher (prod scigraph) and not matrix (dev scigraph). the new ontology file doesn't seem to have propagated up to production yet but i do see resource results in autocomplete, but no resource in categories.

**Comment by twhetzel** [comment]
@debanks Do you plan to leave alpha and stage both pointing to prod scigraph or should @ccondit push this file and the category assignments (#85) to prod scigraph?

**Comment by debanks** [comment]
Previously matrix didn't seem stable enough as we were heading into testing so I swapped everything from it. Alpha is switched over now

**Comment by twhetzel** [comment]
Thanks, not the labels on alpha look as expected so far.
