### ISSUE TITLE
update feature-phenotype call with missing annotations

### ISSUE THREAD

**Issue by nlwashington** [SciCrunch/SciGraph#88]
the /feature/id/phenotype template query should have associations, but is missing them.

for example, when querying for /feature/MGI:1857543/phenotypes

there are no associations to this feature.  but, the massive graph should include the association nodes that link the phenotype to any parts of the genotype from which the association to the feature is inferred.

for the case above, we know that the phenotypes like MP:0000913 are inferred to MGI:1857543  via genotypes like MGI:2167129.  therefore, the association between the genotype-phenotype should be included in the graph returned.

**Comment by nlwashington** [comment]
related to #83

**Comment by ccondit** [comment]
Should be resolved with `evidence=true`...
