### ISSUE TITLE
Autocomplete with cateogry parameter is broken

### ISSUE THREAD

**Issue by kshefchek** [SciCrunch/SciGraph#91]
Adding a category to an autocomplete query seems to break the query, for example:

http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/SHH?limit=20&searchSynonyms=true&searchAbbreviations=false&searchAcronyms=false&includeDeprecated=false

http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/SHH?limit=20&searchSynonyms=true&searchAbbreviations=false&searchAcronyms=false&includeDeprecated=false&category=gene

**Comment by ccondit** [comment]
Resolved - was just a configuration issue on geoffrey.
