### ISSUE TITLE
missing depiction edges

### ISSUE THREAD

**Issue by nlwashington** [SciCrunch/SciGraph#94]
for the node, EOM_01f3cc71dd4c3b9d
i am not seeing the foaf:depiction edges in the vocabulary or graph services:
http://rosie.crbs.ucsd.edu:9000/scigraph/vocabulary/id/EOM_01f3cc71dd4c3b9d

here is the full ttl for this item:
<pre>
OBO:EOM_01f3cc71dd4c3b9d a owl:Class ;
    rdfs:label "Foot, Osseous Syndactyly of" ;
    OBO:IAO_0000115 "Lateral (A/P) fusion of the digits (phalanges and/or metatarsals) by hard tissue (cartilage and/or bone)." ;
    dc:comment "Metatarsal syndactyly can be demonstrated by the inability to independently manipulate the two metatarsals (see Polydactyly, mesoaxial for a description of this maneuver) or the continuity of two metatarsals is demonstrated [Biesecker, [2007]]. The description should include the bones that are fused. Osseous syndactyly is distinct from Symphalangism, where the phalanges are fused at the joint longitudinally (P/D axis). The exact nature of the bony anomaly may not be definable without X-ray evidence. Note that the unqualified term syndactyly is no longer allowed as it is unclear whether this refers to bony or cutaneous syndactyly." ;
    OIO:hasRelatedSynonym "Syndactyly (without adjective)" ;
    owl:equivalentClass OBO:HP_0010717 ;
    foaf:depiction "http://elementsofmorphology.nih.gov/images/terms/Foot,Osseous_Syndactyly_of-large.jpg",
        "http://elementsofmorphology.nih.gov/images/terms/Foot,Osseous_Syndactyly_of-small.jpg" ;
    foaf:page "http://elementsofmorphology.nih.gov/index.cgi?tid=01f3cc71dd4c3b9d" .
</pre>

i also notice that foaf:depiction is not in the relationship call:
http://rosie.crbs.ucsd.edu:9000/scigraph/graph/relationship_types

does it need to get added as an object_property?  or does it need to get added as a special edge to vocabulary services? @cmungall should this be part of the vocabulary service?

**Comment by ccondit** [comment]
It's in the graph - just as a node property:
http://rosie.crbs.ucsd.edu:9000/scigraph/graph/EOM_01f3cc71dd4c3b9d.gml

How are you expecting this to be translated to an edge?

**Comment by nlwashington** [comment]
oh!  perfect.
